### ISSUE TITLE
#2 - Inception : Feedback

### ISSUE THREAD

**Issue by kob-e** [Nir-Cohen/Bishvil#12]
לא מפורט בכלל, מאוד כללי ומה שכתוב יכול להוות מידע עבור כל פרויקט. 
עוד טיפה מידע על כל חבר צוות, במקום לרשום מה כולם יודעים ביחד לרשום כל אחד מה הוא מתמחה. 
חסר סיכונים.

**Comment by Nir-Cohen** [comment]
תודה, נתקן ונעשה לך תיוג שתראה שוב

**Comment by kob-e** [comment]
@Nir-Cohen מתי תתייגו אותי שוב לשינויים?

**Comment by Nir-Cohen** [comment]
@kob-e השינויים בוצעו במסמכים Incetpion / Team
