### ISSUE TITLE
Mission 3 - SRS: Feedback

### ISSUE THREAD

**Issue by kob-e** [Nir-Cohen/Bishvil#14]
## TODO:
- Please attach here the Client review.
https://drive.google.com/open?id=0BzHnFrVO7-T5Nnk5TDNNemJSeEU
## סיכום פגישתנו:
יש מוצר ברור, סיכונים לא ידועים, כנראה לקוח לא סגור עד הסוף מה המוצר. יש פתרונות קיימים למוצר.

**Comment by Nir-Cohen** [comment]
@kob-e לא הבנתי מהם הפתרונות הקיימים למוצר?
אנחנו מחכים לתשובה של הבנות שם.

**Comment by Nir-Cohen** [comment]
@kob-e העלתי קובץ לדרייב.. זה הדרישות שלהם למוצר
