### ISSUE TITLE
Update Inception Page

### ISSUE THREAD

**Issue by Nir-Cohen** [Nir-Cohen/Bishvil#31]
[Our Inception](https://github.com/Nir-Cohen/Bishvil/wiki/Planing---Inception)
חסר לנו מספר דברים: שמתי לך קישור ישר לעמוד שלנו.
בטבלת סיכונים - להוסיף עוד סיכונים שחשבנו עליהם מאוחר יותר
תרשים מצבים - מורחב!!
טבלה של קצב התקדמות

**Comment by TalYehoshua** [comment]
חסר לנו מספר דברים: שמתי לך קישור ישר לעמוד שלנו. **DONE**
בטבלת סיכונים - להוסיף עוד סיכונים שחשבנו עליהם מאוחר יותר **DONE**
תרשים מצבים - מורחב!! **DONE**
טבלה של קצב התקדמות **DONE**
