### ISSUE TITLE
rewrite user manual

### ISSUE THREAD

**Issue by Nir-Cohen** [Nir-Cohen/Bishvil#38]
update the info

**Comment by Nir-Cohen** [comment]
@roysha1 @netanelm54 @TalYehoshua @EddieLavian 
done! take a look!

**Comment by roysha1** [comment]
רמה גבוהה מאוד אחי

בתאריך 4 במאי 2017 00:17,‏ "Nir-Cohen" <notifications@github.com> כתב:
